/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

import java.awt.Font;

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  distanceText = new GLabel(this, 0.1*width, 0.1*height, 0.8*width, 0.1*height);
  distanceText.setFont(new Font("Impact", Font.PLAIN, 36));
  distanceText.setText("3800 Km");
  distanceText.setTextBold();
  distanceText.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel distanceText; 