/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

 public void button2_click1(GButton button, GEvent event) {
  /*if(!buttonsDict.Contains(button)) {
    return
  }

  Add value
  Raise Price
  Raise Power

  */
 }

import java.awt.Font;
Font title = new Font("Impact", Font.PLAIN, 42);
Font subTitle = new Font("Impact", Font.PLAIN, 24);

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.RED_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  distanceText = new GLabel(this, 0.1*width, 0.05*height, 0.8*width, 0.2*height);
  distanceText.setFont(title);
  distanceText.setText("0 m");
  distanceText.setTextBold();
  distanceText.setOpaque(false);
  
  speedText = new GLabel(this, 0.1*width, 0.75*height, 0.8*width, 0.25*height);
  speedText.setFont(title);
  speedText.setText("0 m/s");
  speedText.setTextBold();
  speedText.setOpaque(false);
  
  shop = new GPanel(this, 0, 0, width, height, "");
  shop.setOpaque(false);
  
  /*panel2 = new GPanel(this, 0, 0, width, height, "");
  panel2.setLocalColorScheme(GCScheme.RED_SCHEME);
  panel2.setOpaque(true);
  button2 = new GButton(this, 0.1*width, 0.75*height, 0.8*width, 0.2*height);
  button2.setText("BUY");
  button2.addEventHandler(this, "button2_click1");
  label2 = new GLabel(this, 0.1*width, 0.05*height, 0.8*width, 0.2*height);
  label2.setFont(title);
  label2.setText("Clic power");
  label2.setOpaque(false);
  label3 = new GLabel(this, 0.1*width, 0.3*height, 0.8*width, 0.2*height);
  label3.setFont(subTitle);
  label3.setText("Price: 100 km");
  label3.setOpaque(false);
  label4 = new GLabel(this, 0.1*width, 0.45*height, 0.8*width, 0.2*height);
  label4.setFont(subTitle);
  label4.setText("Curr pow: 10 m");
  label4.setOpaque(false);
  panel2.addControl(button2);
  panel2.addControl(label2);
  panel2.addControl(label3);
  panel2.addControl(label4);
  shop.addControl(panel2);*/
}

// Variable declarations 
// autogenerated do not edit
GLabel distanceText; 
GLabel speedText;
GPanel shop; 
GPanel panel2; 
GButton button2; 
GLabel label2; 
GLabel label3; 
GLabel label4; 